sequenceDiagram
    autonumber
    participant Sample1
    participant Sample2
    participant Sample3
    Sample1 ->> Sample2: requestMessage<br/>L:3
    Note over Sample2: State:Executing<br/>L:5
    Sample2 ->> Sample3: requestMessage<br/>L:7
    Note over Sample3: state:Executing<br/>L:8
    Sample3 ->> Sample2: notifyMessage<br/>L:11
    Sample2 ->> Sample1: notifyMessage<br/>L:12
